[build]
  functions = "netlify/functions"   
  publish = "dist"                 
  command = "npm run build"         
  
[dev]
  functions = "netlify/functions"  
  command = "npm run dev"             
  targetPort = 3000
  